packages:
  - core/cli
  - core/dicc

catalog:
  '@eslint/compat': ^1.4.0
  '@eslint/js': ^9.37.0
  '@tsconfig/node22': ^22.0.2
  '@types/node': ^22.18.10
  eslint: ^9.37.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-unused-imports: ^4.2.0
  globals: ^16.4.0
  prettier: ^3.6.2
  publint: ^0.3.14
  ts-node: ^10.9.2
  tsdown: ^0.15.7
  typescript: ^5.9.3
  typescript-eslint: ^8.46.1

injectWorkspacePackages: true
linkWorkspacePackages: true
